[package]
name = "grepolis_api_reflector"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
bytes = "1.10.0"
lazy_static = "1.5.0"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["gzip", "deflate"] }
tokio = { version = "1.43.0", features = ["full"] }
