version: "3.5"  # debian...
services:
  grepolis_api_reflector:
    build: "./"
    container_name: "grepolis_api_reflector"
    expose: 
      - 3000
    volumes: 
      - "/data/grepolis_api_reflector:/cache"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: "unless-stopped"
    networks:
      - internet

networks:
  internet:
    name: "internet"
