version: "3.3"  # debian...
services:
  grepolis_api_reflector:
    build: "./"
    container_name: "grepolis_api_reflector"
    expose: 
      - 3000
    volumes: 
      - "/data/grepolis_api_reflector:/cache"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: "unless-stopped"

# network not required, since we map the port to the host
# alternatively we could also put this behind caddy
# for now I'll leave the port mapping in
